# Please check the parameters, and adjust them according to your circumstance

# Project name
PROJECT: "Biscutella_remapping_varia"

# ================== Control of the workflow ==================

## Do you need to do quality control?
QC: no # "yes" or "no"

## Do you need to do trimming?
TRIMMING: "yes" # "yes" or "no"?


GENOME:
    "/data/users/rchoudhury/Biscutella_Genomes/data/Varia_review2.FINAL.Syri.fa"


# set SCAFFOLDS as "ALL" if you want to run on all scaffolds :: impliment only if limited number of scaffolds, else split snakemake into multiple jobs :: test it
# else give a txt file with names of scaffolds (one per line)
SCAFFOLDS:
    "ALL"

METAFILE:
    "/data/users/rchoudhury/snakeSNPcalling/configs/metadata_fixed.tsv"

INPUT:
    "/data/users/rchoudhury/Biscutella_wgs_remapping_2025/data/raw/all"
FINALOUTPUT: /data/users/rchoudhury/snakeSNPcalling/results

# Directory where log files for each pipeline step will be stored
log_folder: "logs"

tmpdir: "tmp"

scatter_mode: "interval" # "chromosome" or "interval"
intervals_dir: "data/intervals"
scatter_count: 100

# Following https://github.com/AndersenLab/wi-gatk/blob/master/main.nf for values
HaplotypeCaller:
  minConfidenceForVariantCalling: "20" # would not be used in haplotypecaller, but instead in genotypegvfs

# Quality by Depth (QD) < 1.5 (for tetraploid), FisherStrand (FS) > 60.0, RMSMappingQuality (MQ) < 40.0, MappingQualityRankSumTest (MQRS) < −12.5, ReadPosRankSum < −8.0, StrandOddsRatio (SOR) > 3.0
  min_depth: 4
  qual: 30.0
  strand_odds_ratio: 3.0
  quality_by_depth: 1.5
  fisherstrand: 60.0
  RMSMappingQuality: 40.0
  MappingQualityRankSumTest: -12.5
  ReadPosRankSum: -8.0
  high_missing: 0.95
  high_heterozygosity: 0.10
  # GQ: 10.0 do not use GQ filter, instead work on depth , 8 for tetra, 4 for dip

GenotypeGVCFs:
  minConfidenceForVariantCalling: "10"

GATK:
  min_depth:
    tetra: 8
    di: 4
  max_depth:
    tetra: 150
    di: 150



FreeBayes:
  chunks: 50000
  theta: 0.001 # mutation rate / expected pairwise nucleotide diversity (freebayes default 0.001)
  max_complex_gap: -1 #  Allow haplotype calls with contiguous embedded matches of up to this length. Set N=-1 to disable clumping. (freebayes default: 3).  Read length/2 should be safe
  use_best_n_alleles: 32 # limit number of alleles to consider; 0 for all.  @TCC for some problematic regions, otherwise runs forever
  min_base_quality: 20 # minimum base quality for variant calling
  min_mapping_quality: 20 # minimum mapping quality for variant calling



Structure:
  # ───── choose run mode ─────
  run_mode: "bestK"        # "fixed"  or  "bestK", changing to always use bestK
  ks: [1, 2, 3, 4, 5]   # always the range you want explored, even when you know the bestK, give a range of at least 3
  bestK: 3          # if run_mode is "fixed", this is the K value to use
  replicates: 10
  burnin: 100000 # Number of burn-in iterations
  mcmc: 1000000 # Total number of iterations
  ploidy: 4 # Ploidy of the organism (default is 2 for diploid)
  time: "2-00:00:00" # Time limit for the job, adjust as needed


PCA:
  # ───── PCA parameters ─────
  ploidy: mixed # "diploid", "tetraploid" or "mixed"